[package]
name = "bitbygit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bitbygit-core = { path = "../bitbygit-core" }
bitbygit-store = { path = "../bitbygit-store" }
bitbygit-tui = { path = "../bitbygit-tui" }

[lints]
workspace = true
